auth:
  username: # Fill the POSTGRESQL_AUTH_USERNAME value in the .env file!
  password: # Fill the POSTGRESQL_AUTH_PASSWORD value in the .env file!
  database: lugvloei

primary:
  persistence:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

replica:
  replicaCount: 0
